# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luna's blog
brief-intro: 月亮月亮酱
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cirnoo.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
zhihu_username:   yue-liang-78-7
github_username:  Cirnoo
email: 9@7at.me

description_footer: 月亮酱的心路历程

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #hygblog
#disqus_shortname: cirnoo

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
# google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
